### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/brow#1]
## TODO 

* [x] Tests for client 
* [x] Tests for worker
* [x] Tests for transport
* [x] Automatically convert all dates/times to predictable format
