### ISSUE TITLE
0.2.0 TODO

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/brow#2]
Mostly bug fixes for data loss based on my flipper cloud instrumentation branch. 

- [x] rename `record` to `push`
- [x] have to flush in client integration test because it drops events on the ground, need to enqueue a shutdown message
- [x] get all the reporter specs for flipper working here or change worker to be like flipper
